const plans = {
    free: {
        name: 'Grátis',
        price: 0,
        limits: {
            links: 3,
            edits: 3,
            qrcodes: 2,
        },
        features: [
            'basic_stats',
            'country_stats_basic',
        ],
    },
    basic: {
        name: 'Básico',
        price: 34.90,
        isPopular: true,
        limits: {
            links: 10,
            edits: 20,
            qrcodes: 10,
        },
        features: [
            'basic_stats',
            'country_stats_basic',
            'hourly_stats',
            'export_csv',
            'traffic_sources',
        ],
    },
    intermediate: {
        name: 'Intermediário',
        price: 59.90,
        limits: {
            links: 500,
            edits: 500,
            qrcodes: 100,
        },
        features: [
            'basic_stats',
            'country_stats_top_10',
            'hourly_stats',
            'export_csv',
            'traffic_sources',
            'geo_details_top_10',
            'utm_tracking',
            'security_analysis',
            'link_edit_history',
            'geo_heatmap',
            'retention_data',
            'device_stats',
        ],
    },
    advanced: {
        name: 'Avançado',
        price: 89.90,
        limits: {
            links: 5000,
            edits: 5000,
            qrcodes: 1000,
        },
        features: [
            'basic_stats',
            'country_stats_all',
            'hourly_stats',
            'export_csv',
            'traffic_sources',
            'geo_details_all',
            'utm_tracking',
            'security_analysis',
            'link_edit_history',
            'geo_heatmap',
            'retention_data',
            'device_stats',
            'custom_domains',
        ],
    },
    custom: {
        name: 'Personalizado',
        price: null,
        limits: {
            links: Infinity,
            edits: Infinity,
            qrcodes: Infinity,
        },
        features: [
            'basic_stats',
            'country_stats_all',
            'hourly_stats',
            'export_csv',
            'traffic_sources',
            'geo_details_all',
            'utm_tracking',
            'security_analysis',
            'link_edit_history',
            'geo_heatmap',
            'retention_data',
            'device_stats',
            'custom_domains',
            'api_access',
        ],
    },
};

module.exports = plans; 